version: 2
jobs:
  checkout_code:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/buckler
  build:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - run: mix local.hex --force
      - run: mix do deps.get
      - run: mix do compile
      - save_cache:
          key: v1-build-{{ checksum ".circle-sha" }}
          paths:
            - ~/buckler/_build
            - ~/buckler/deps
  test:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-build-{{ checksum ".circle-sha" }}
      - run: mix do deps.get
      - run:
          working_directory: ~/buckler/apps/buckler_bot
          name: Test
          environment:
            TELEGRAM_TOKEN: 123
            DB_NAME: testdb
          command: mix test
  deploy:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-build-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - gemfile-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Ruby Dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Deploy Master to Server
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              DEPLOY_TARGET=45.32.241.56 bundle exec mina deploy
            fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
