version: 2
jobs:
  checkout_code:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/buckler
  build:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - run:
        name: install hex
        command: mix local.hex --force
      - run:
        name: download geps
        run: mix do deps.get
      - save_cache:
        key: v1-deps-{{ checksum ".circle-sha" }}
        paths:
          - ~/buckler/deps
  test:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-deps-{{ checksum ".circle-sha" }}
      - run: mix do deps.get
      - run:
          name: Test
          command: TELEGRAM_TOKEN=123 DB_NAME=testdb cd apps/buckler_bot && mix test
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
