version: 2
jobs:
  build:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
