version: 2
jobs:
  build:
    working_directory: ~/buckler
    docker:
      - image: noma4i/docker-elixir:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - type: cache-restore
        key: gemfile-{{ checksum "Gemfile.lock" }}
      - type: shell
        name: Install Bundler
        command: gem install bundler
      - type: shell
        name: Install Ruby Dependencies
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - type: cache-save
        key: gemfile-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - deploy:
          name: Deploy Master to Server
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              DEPLOY_TARGET=45.32.241.56 mina deploy
            fi
